config/routes.rb
Rails.application.routes.draw do
  get 'user_apps/index'
  get 'user_apps/show'
  get 'user_apps/new'
  get 'user_apps/edit'

  devise_for :users
  get "/my_profile/edit", to: "users#edit", as: "edit_my_profile"
  patch "/my_profile/edit", to: "users#update", as: "update_my_profile"
  resources :user_apps

  root to: "pages#home"
  get 'mes_demarches', to: 'user_apps#index'
  get 'new_demarche', to: 'user_apps#new'


  get '/demenagement', to: 'users#je_demenage', as: 'je_demenage'
  get '/chanement_rib', to: 'users#rib', as: 'rib'

  # Correction de cette ligne
  resources :user_apps

end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  # Defines the root path route ("/")
  # root "posts#index"

app/models/app.rb
class App < ApplicationRecord


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :apps
  has_many :user_apps

  has_one_attached :photo


         # Callback to encrypt RIB before saving

  def encrypt_rib
    if rib != nil
      rib.gsub(/.(?=.{2})/, '*')
    end
  end
end

app/models/user_app.rb
class UserApp < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :app

  # Validations (si nécessaires)
  validates :user_id, presence: true
  validates :app_id, presence: true
  # Ajoute d'autres validations si nécessaire
  def encrypt_rib
    if rib != nil
      rib.gsub(/.(?=.{2})/, '*')
    end
  end
  # Autres méthodes et logiques liées à UserApp
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :address, :photo, :rib])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :address, :photo, :rib])
  end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  before_action :set_app, only: [:show, :edit, :update, :destroy]


  def index
    @apps = App.all
  end

  def show
  end

  def new
    @app = App.new
    @app.user = current_user
  end

  def create
    @app = App.new(app_params)
    if @app.save
      redirect_to @app, notice: 'App was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @app.update(app_params)
      redirect_to @app, notice: 'App was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @app.destroy
    redirect_to apps_url, notice: 'App was successfully destroyed.'
  end

  private

  def set_app
    @app = App.find(params[:id])
  end

  def app_params
    params.require(:app).permit(:name, :description, :price, :category, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
    @query = params[:query]
    @user = current_user
    @user_apps = current_user.user_apps

    if @query.present?
      @user_apps = @user_apps.joins(:app).where("apps.name ILIKE ?", "%#{@query}%")
      # @user_apps = @user_apps.join(:app).where.not("user_apps.rib ILIKE ? or user_apps.phone ILIKE ? or user_apps.address ILIKE ? or user_apps.email ILIKE ? ", "%#{@query}%", "%#{@query}%", "%#{@query}%", "%#{@query}%")
      @user_apps = @user_apps.where.not("user_apps.address ILIKE ?", "%#{@query}%")

    end


    @user_apps = @user_apps.map do |user_app|
      changes_count = 0
      if current_user
        changes_count += 1 if user_app.address.present? && user_app.address != current_user.address
        changes_count += 1 if user_app.email.present? && user_app.email != current_user.email
        changes_count += 1 if user_app.phone.present? && user_app.phone != current_user.phone
        changes_count += 1 if user_app.rib.present? && user_app.rib != current_user.rib
      end
      [user_app, changes_count]
    end

  end

end

app/controllers/user_apps_controller.rb
class UserAppsController < ApplicationController
  before_action :set_user_app, only: [:show, :edit, :update, :destroy]

  # GET /user_apps
  def index
    @user_apps = UserApp.all # Charge toutes les user_apps
  end

  # GET /user_apps/:id
  def show
  end

  # GET /user_apps/new
  def new
    @user_app = UserApp.new
  end

  # POST /user_apps
  def create

    @user_app = UserApp.new(user_app_params)
    @user_app.user = current_user
    if @user_app.save
      redirect_to root_path, notice: 'UserApp was successfully created.'
    else
      render :new
    end
  end

  # GET /user_apps/:id/edit
  def edit
    # @user_app est déjà défini grâce à la méthode set_user_app
  end

  # PATCH/PUT /user_apps/:id
  def update

    if @user_app.update(user_app_params)
      redirect_to root_path, notice: 'UserApp was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_apps/:id
  def destroy
    @user_app = current_user.user_apps.find(params[:id])
    @user_app.destroy
    redirect_to root_path, status: :see_other
  end


  private

  # Méthode pour trouver l'objet UserApp en fonction de l'ID passé dans les paramètres
  def set_user_app
    @user_app = UserApp.find(params[:id])
  end

  # Méthode strong parameters pour permettre uniquement les attributs autorisés
  def user_app_params
    params.require(:user_app).permit(
      :id, :user_id, :app_id, :phone, :address, :email, :date_prelevement, :date_renouvellement, :montant, :rib, :name
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update]

  # GET /users/:id/edit
  def edit
    @user = current_user
  end

  # PATCH/PUT /users/:id
  def update
    if @user.update(user_params)
       redirect_to root_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :first_name, :rib, :last_name, :phone, :address, :photo, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_exists?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end
end

app/views/apps/new.html.erb
<%= render 'pages/coordonnées' %>
<%= form_with(model: @app, local: true) do |form| %>
  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="field">
    <%= form.label :tuto %>
    <%= form.text_field :tuto %>
  </div>

  <div class="field">
    <%= form.label :url_redirection %>
    <%= form.text_field :url_redirection %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizer</title>
    <%= csp_meta_tag %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background:#FEFCFB">
    <%= render "shared/navbar" %>
    <div class= "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_coordonnées.html.erb
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1501556466850-7c9fa1fccb4c?w=600&auto=format&fit=cro[…]3wxMjA3fDB8MHxzZWFyY2h8Nnx8b3JnYW5pemF0aW9ufGVufDB8fDB8fHww);">

    <h3 id="titrebanner">L'administratif n'a jamais été aussi simple</h3>

  </div>



  <div class="coordonnees" >

    <% if user_signed_in? %>
            <h2 class= "h2-titre">Mes coordonnées actuels</h2>
            <hr class="thick-hr">
            <div class="row">
   <div class="boutton d-flex justify-content-end" id="je-change-mes-coordonnees">
      <%= link_to edit_my_profile_path do %>
        <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
    </div>
    <div class="card-text d-flex align-items-baseline justify-content-around">
      <div >
        <ul >
        <li class="card-texts">
          <i class="fa-regular fa-address-card" ></i>
          <%= "#{current_user.last_name} #{current_user.first_name}" %>
        </li class="card-texts">
          <li class="card-texts"><i class="fa-regular fa-user"style= "margin-right: 10px"></i><%= current_user.email %></li>
        </ul>
      </div>
      <div >
        <ul>
          <li class="card-texts"><i class="fa-solid fa-house" style= "margin-right: 10px"></i><%= current_user.address %></li>
          <li class="card-texts"><i class="fa-solid fa-phone" style= "margin-right: 10px"></i><%= current_user.phone %></li>
          <div class="d-flex" data-controller="rib">
          <li class="card-texts"><i class="fa-solid fa-money-check" style= "margin-right: 10px"></i></li>
          <span class= " d-none info" data-rib-target="decrypt"><%= current_user.rib %></span>
        <span class="info" data-rib-target="encrypt"><%= current_user.encrypt_rib %></span>
        <i class="fa-solid fa-eye" data-action="click->rib#toggle" style="margin-left: 10px;"></i>
        </ul>
      </div>
    </div>


    </div>
    </div>
     <% end %>

app/views/pages/home.html.erb
<%= render 'pages/coordonnées' %>
<div class="search-bar d-flex align-items-center" id="searchdesign">
  <%= form_with url: root_path, method: :get, local: true, class: "d-flex w-100" do |form| %>
    <%= form.text_field :query, placeholder: "Entrez votre recherche", class: "form-control me-2" %>
    <%= form.submit "Rechercher", class: "submit-button" %>
  <% end %>
</div>
<hr id="barre">
<h1 id="titre">Vos démarches</h1>
<hr class= thick-hr>
<div class="card-container">
  <div id="ajouter-une-demarche">
    <%= link_to new_demarche_path,class: "submit-button"   do %>
      <i class="fa-solid fa-file-circle-plus"></i>
      Ajouter une démarche
    <% end %>
  </div>
  <%= render 'user_apps/cards' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <!-- Logo à gauche -->
    <a class="navbar-brand" href="/">
      <%= image_tag "logoapp.jpg", class: "logo"%>
    </a>

    <!-- Titre centré -->
    <div class="mx-auto">
      <span class="navbar-title">Organizer</span>
    </div>

    <!-- Liens d'authentification Devise à droite -->
    <div class="ml-auto">
      <% if user_signed_in? %>
      <div style="display: flex; align-items: center;">
       <% if current_user.photo.present? %>
    <%= image_tag(current_user.photo, style: "border-radius: 50%; margin-right: 20px; width: 50px; height: 50px; object-fit: cover;") %>
  <% else %>
    <i class="fa-regular fa-circle-user" style="margin-right: 20px; font-size: 30px"></i>
  <% end %>
        <span style="margin-right: 50px">Bienvenue, <%= current_user.first_name %>!</span>
        <%= link_to 'Déconnexion', destroy_user_session_path, data: {turbo_method: "delete"} , class: "btn btn-outline-dark ml-2" %>
      </div>
      <% else %>
        <%= link_to 'S\'inscrire', new_user_registration_path, class: "btn btn-outline-primary ml-2" %>
        <%= link_to 'Connexion', new_user_session_path, class: "btn btn-outline-success ml-2" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/user_apps/_cards.html.erb
<div class="container-all" data-controller="hello">
  <div class="fix">
    <% @user_apps.each do |user_app_data| %>
      <% user_app, changes_count = user_app_data %>
      <div class="card-container card-app" data-action="click->hello#grow">
        <div class="d-flex gap-3">
          <div id="logo-card">
            <%= image_tag "#{user_app.app.name.downcase.gsub(" ","")}.jpg", alt: user_app.name, class: "card-img-top" if asset_exists?("#{user_app.app.name.downcase.gsub(" ","")}.jpg") %>
            <%= image_tag "#{user_app.app.name.downcase.gsub(" ","")}.png", alt: user_app.name, class: "card-img-top" if asset_exists?("#{user_app.app.name.downcase.gsub(" ","")}.png") %>
          </div>
          <div class="name-count">
            <span class="fs-3"><%= user_app.app.name %></span>
            <% if changes_count > 0 %>
              <span class="change-count">
                <i class="alert-icons fa-solid fa-circle-exclamation"></i>
                <%= changes_count %> changement<%= 's' if changes_count > 1 %>
              </span>
            <% end %>
          </div>

          <div class="app-info">
            <p class="pe-3">
              <strong>Adresse </strong> <%= current_user.address %>
            </p>
            <p class="pe-5">
              <strong>Email </strong> <%= current_user.email %>
            </p>
            <%= link_to edit_user_app_path(user_app) do %>
              <i class="fa-regular fa-pen-to-square"></i>
            <% end %>
            <%= link_to user_app_path(user_app), data: { turbo_method: :delete, confirm: 'Êtes-vous sûr de vouloir supprimer cette application ?' }, class: 'custom-icon-link pe-4' do %>
              <i class="delete fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
        <div class="card little-card" id="userCard" style="cursor: pointer; width: 100%;">
          <div id="moreInfo" style="display: none;">
            <!-- Contenu caché affiché après clic -->
            <div class="card-text d-flex align-items-baseline justify-content-around">
              <div>
                <p class="card-texts">
                  <strong>Adresse</strong> <%= user_app.address %>
                  <% if user_app.address != current_user.address %>
                    <i class="alert-icon fa-solid fa-circle-exclamation" title="Adresse non à jour"></i>
                  <% end %>
                </p>
                <p class="card-texts">
                  <strong>Email </strong> <%= user_app.email %>
                  <% if user_app.email != current_user.email %>
                    <i class="alert-icon fa-solid fa-circle-exclamation" title="Email non à jour"></i>
                  <% end %>
                </p>
                <p class="card-texts">
                  <strong>Téléphone </strong> <%= user_app.phone %>
                  <% if user_app.phone != current_user.phone %>
                    <i class="alert-icon fa-solid fa-circle-exclamation" title="Téléphone non à jour"></i>
                  <% end %>
                </p>
                <p class="card-texts" data-controller="rib">

                  <strong>RIB </strong>
                  <span class="d-none info" data-rib-target="decrypt"><%= user_app.rib %></span>
                  <span class="info" data-rib-target="encrypt"><%= user_app.encrypt_rib %></span>
                  <i class="fa-solid fa-eye" data-hello-target="oeil" data-action="click->rib#toggle" style="margin-left: 10px;"></i>

                  <% if user_app.rib != current_user.rib %>
                    <i class="alert-icon fa-solid fa-circle-exclamation" title="RIB non à jour"></i>
                  <% end %>
                </p>
              </div>
              <div>
                <p class="card-texts">
                  <strong>Date de prélèvement </strong> <%= user_app.date_prelevement %>
                </p>
                <p class="card-texts">
                  <strong>Date de renouvellement </strong> <%= user_app.date_renouvellement %>
                </p>
                <p class="card-texts">
                  <strong>Montant </strong> <%= number_to_currency(user_app.montant, unit: "€") %>
                </p>
              </div>
            </div>
            <div class="redirect_links d-flex justify-content-end">
              <% if user_app.app.url_redirections.present? %>
                <% if user_app.app.url_redirections["rib"].present? %>
                  <%= link_to user_app.app.url_redirections["rib"], target: "_blank", class: "submit-button" do %>
                    <i class="redirect fa-solid fa-building-columns mr-2"></i> Changer votre rib sur le site  <%= user_app.app.name %>
                  <% end %>
                <% end %>
                <% if user_app.app.url_redirections["address"].present? %>
                  <%= link_to user_app.app.url_redirections["address"], target: "_blank", class: "submit-button" do %>
                    <i class="redirect fa-solid fa-house mr-2"></i> Changer votre adresse sur le site <%= user_app.app.name %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user_apps/edit.html.erb
<%= render 'pages/coordonnées' %>
<div class="formulaire" data-controller="remove">
  <%= simple_form_for @user_app do |f| %>
    <!-- Le champ Application ne sera pas modifiable -->
    <div class="form-group" id="appname" data-remove-target="input">
      <h2 class= "h2-titre"><%= @user_app.app.name %></h2>
    </div>
      <hr class="thick-hr"><!-- Affiche le nom de l'application -->

    <!-- Nom modifiable -->
    <div class="form-group">
            <div id= "modifform" class="input-label-bold">
              <%= f.input :name, placeholder: "Nom", label: "Nom", input_html: { value: current_user.first_name }, class: "inp-margin" %>
            </div>

      </div>

    <!-- Téléphone modifiable -->
    <div class="form-group">
      <div id= "modifform" class="input-label-bold">
              <%= f.input :phone, placeholder: "Téléphone", label: "Téléphone", input_html: { value: current_user.phone }, class: "inp-margin" %>
      </div>

    </div>

    <!-- Adresse modifiable -->
    <div class="form-group-text">
      <div id= "modifform" class="input-label-bold">
              <%= f.input :address, placeholder: "Adresse", label: "Adresse", input_html: { value: current_user.address }, class: "inp-margin" %>
      </div>
      </div>


    <!-- Email modifiable -->
    <div class="form-group-text">
      <div id= "modifform" class="input-label-bold">
              <%= f.input :email, placeholder: "Email", label: "Email", input_html: { value: current_user.email }, class: "inp-margin" %>
      </div>
    </div>

    <!-- RIB modifiable avec icône de visibilité -->
    <div class="form-group" data-controller="rib">

      <div id= "modifform" class="input-label-bold">
              <%= f.input :rib, placeholder: "RIB", label: "RIB", input_html: { value: current_user.rib, class: "d-none", data: { rib_target: "decrypt" } }, class: "inp-margin" %>
        </div>
        <span class="info" data-rib-target="encrypt"><%= current_user.encrypt_rib %></span>
        <i class="fa-solid fa-eye" data-action="click->rib#toggle"></i>

    </div>

    <!-- Dates de prélèvement et de renouvellement -->
      <div id="date" class="input-label-bold">
        <%= f.input :date_prelevement, placeholder: "Date de prélèvement", label: 'Date de prélèvement', as: :date, html5: true %>
        <%= f.input :date_renouvellement, placeholder: "Date de renouvellement", label: 'Date de renouvellement', as: :date, html5: true %>
      </div>


    <!-- Montant modifiable -->
    <div id="montant" class="input-label-bold"  >
      <%= f.input :montant, placeholder: "Montant", label: "Montant" %>
    </div>

    <!-- Bouton Enregistrer -->
    <div id="enregistrer" class="text-center">
      <%= f.button :submit, value: 'Enregistrer', class: 'submit-button' %>
    </div>

  <% end %>
</div>

app/views/user_apps/index.html.erb
<%= render 'pages/coordonnées' %>
<div>
<h1>Toutes vos démarches</h1>
<div class="d-flex w-100 justify-content-between align-items-center">

  <div class="boutton d-flex justify-content-center" id="buttons">

    <div class="boutton d-flex justify-content-center" id="je-demenage">
      <%= link_to je_demenage_path, class: 'btn btn-flex', style: 'background-color: #FFD18E; color: white;' do %>
        <i class="fa-solid fa-dolly" style="font-size: 30px;"></i>
        Je déménage
      <% end %>
    </div>

    <div class="boutton d-flex justify-content-center" id="je-change-de-rib">
      <%= link_to rib_path, class: 'btn btn-flex', style: 'background-color: #FFD18E; color: white;' do %>
        <i class="fa-solid fa-comments-dollar" style="font-size: 30px;"></i>
        Je change de RIB
      <% end %>
    </div>

    <div class="boutton d-flex justify-content-center" id="je-change-mes-coordonnees">
      <%= link_to edit_user_registration_path, class: 'btn btn-flex', style: 'background-color: #FFD18E; color: white;' do %>
        <i class="fa-solid fa-address-card" style="font-size: 30px;"></i>
        Je change mes coordonnées
      <% end %>
    </div>


</div>

<div class="d-flex justify-content-center mt-3">
  <%= link_to 'Retour', root_path, class: 'btn btn-primary' %>
</div>
</div>

app/views/user_apps/show.html.erb
<h1>UserApps#show</h1>
<p>Find me in app/views/user_apps/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render 'pages/coordonnées' %>
<h1 id="titre">Modifier mes coordonnées</h1>
<%= simple_form_for @user, url: update_my_profile_path, method: :patch do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "erreur") %> interdite(s) de sauvegarder :</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="formulaires" data-controller="remove">
   <div class="d-flex justify-content-between"  style="gap:20px;">
    <div class="edit-user">
      <div class="form-group input-label-bold">
        <%= f.input :first_name, label: 'Prénom'  %>
      </div>

      <div class="form-group input-label-bold">
        <%= f.input :last_name, label: 'Nom'   %>
      </div>

      <div class="form-group input-label-bold">
        <%= f.input :email, label: 'Email'  %>
      </div>
    </div>

    <div class="edit-user">
      <div class="form-group input-label-bold">
        <%= f.input :phone, label: 'Téléphone'  %>
      </div>

      <div class="form-group input-label-bold">
        <%= f.input :address, label: 'Adresse'  %>
      </div>

      <div class="form-group input-label-bold">
        <%= f.input :rib, label: 'RIB'  %>
      </div>
    </div>

    <div class="form-group input-label-bold photo-column">
      <%= f.input :photo, as: :file %>
      <%= image_tag(current_user.photo, style: "border-radius: 50%; margin-right: 20px; width: 90px; height: 90px; object-fit: cover;") %>
    </div>
  </div>
    <div id="enregister">
      <%= f.button :submit, value: 'Enregistrer', class:'submit-button' %>
    </div>
</div>


  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/je_demenage.html.erb
<%= render 'pages/coordonnées' %>
<h2>Applications liées à des adresses différentes</h2>

<% if @different_address_apps.any? %>
  <ul>
    <% @different_address_apps.each do |user_app| %>
      <div class="app-card">
    <div class="app-card-header">
      <h3><% user_app.name %></h3> <!-- Utilise `user_app` au lieu de `@user_app` -->
      <p><% user_app.app.name if user_app.app %></p> <!-- Vérifie que `user_app.app` n'est pas nil -->
    </div>
            <div class="card mb-3" id="userCard" style="cursor: pointer; width: 100%;">

                <!-- Contenu minimal affiché initialement -->
                <h5 class="card-title"><%= user_app.app.name %></h5>
                <p class="card-text"><strong>Adresse :</strong> <%= user_app.address %></p>
                <p class="card-text"><strong>Email :</strong> <%= user_app.email %></p>

                <%= link_to 'Supprimer', user_app_path(user_app),  data: { turbo_method: :delete, confirm: 'Êtes-vous sûr de vouloir supprimer cette application ?' }, class: 'btn btn-danger' %>
              <div id="moreInfo" style="display: none;">

                <!-- Contenu caché affiché après clic -->
                  <p class="card-text"><strong>Téléphone :</strong> <%= user_app.phone %></p>
                  <p class="card-text"><strong>Date de prélèvement :</strong> <%= user_app.date_prelevement %></p>
                  <p class="card-text"><strong>Date de renouvellement :</strong> <%= user_app.date_renouvellement %></p>
                  <p class="card-text"><strong>Montant :</strong> <%= number_to_currency(user_app.montant, unit: "€") %></p>
                  <p class="card-text"><strong>RIB :</strong> <%= user_app.encrypt_rib %></p>
              </div>
              </div>
            </div>
    <% end %>
  </ul>
<% else %>
  <p>Aucune application avec une adresse différente.</p>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/rib.html.erb
<%= render 'pages/coordonnées' %>
<% if @different_rib_apps.any? %>
  <ul>
    <% @different_rib_apps.each do |user_app| %>
      <div class="app-card">
    <div class="app-card-header">
      <h3><%= user_app.name %></h3> <!-- Utilise `user_app` au lieu de `@user_app` -->
      <p><%= user_app.app.name if user_app.app %></p> <!-- Vérifie que `user_app.app` n'est pas nil -->
    </div>
    <div class="app-card-details">
      <p><strong>Téléphone :</strong> <%= user_app.phone %></p>
      <p><strong>Adresse :</strong> <%= user_app.address %></p>
      <p><strong>Email :</strong> <%= user_app.email %></p>
      <p><strong>Date de prélèvement :</strong> <%= user_app.date_prelevement %></p>
      <p><strong>Date de renouvellement :</strong> <%= user_app.date_renouvellement %></p>
      <p><strong>Montant :</strong> <%= number_to_currency(user_app.montant, unit: "€") %></p>
      <p><strong>RIB :</strong> <%= user_app.encrypt_rib %></p>
    </div>
  </div>
    <% end %>
  </ul>
<% else %>
  <p>Tout les RIB sont identiques.</p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>